### ISSUE TITLE
使用Swoole\Database::TYPE_CLMysql Mysql proxy中断(接收失败)

### ISSUE THREAD

**Issue by ndj888** [matyhtf/framework#156]
查看源代码\libs\Swoole\Client\CLMySQL.php:121 调用 CLPack::pack 生成$pack成功，包含信息。
\libs\Swoole\Client\CLMySQL.php:133 调用 		$r = self::getPack($sign, $conn_id); 出错 

\libs\Swoole\Client\CLMySQL.php:80 ，执行 $data = @self::$conninfo[$conn_id][self::CONNINFO_F_conn]->recv();
$data 得到为false 
进入\libs\Swoole\Client\CLMySQL.php:85 return false

由于Object(Swoole_client)->recv() 方法属于C拓展，不方便调试，特此反饋问题。在改为PDO或Mysqli时，可以正确获取数据。

系统环境：
swoole-2.0.7
php7.1.3
swoole/framework 最新版本

swoole.ini 配置
[request]
default_page = "index.html"

[server]
host = "0.0.0.0"
port = 8888
max_request = 2000
worker_num = 1
webroot = 'http://127.0.0.1:9501'
document_root = "/usr/src/myapp"
process_rename = 1
keepalive = 1
;gzip_open = 1
user = www-data
expire_open = 1

[session]
cookie_life = 1800
session_life = 1800

[access]
deny_dir = "libs,class,templates"
static_dir = "static/,"
static_ext = "js,jpg,gif,png,css,html"
dynamic_ext = "php"
post_maxsize = 2000000

[apps]
charset = "utf-8"
;auto_reload = 1
apps_path = "/usr/src/myapp/apps"
;是否处理静态文件
do_static = on

// DB 配置

<?php
$db['master'] = array(
    'type'       => Swoole\Database::TYPE_CLMysql,
    'host'       => "192.168.1.240",
    'port'       => 3306,
    'dbms'       => 'mysql',
    'engine'     => 'InnoDB',
    'user'       => "****",
    'passwd'     => "****",
    'name'       => "****",
    'charset'    => "utf8",
    'setname'    => true,
    'persistent' => true, //MySQL长连接
    'use_proxy'  => false,  //启动读写分离Proxy
    'slaves'     => [

    ]
);

$db['slave'] = array(
    'type'       => Swoole\Database::TYPE_MYSQLi,
    'host'       => "127.0.0.1",
    'port'       => 3306,
    'dbms'       => 'mysql',
    'engine'     => 'MyISAM',
    'user'       => "root",
    'passwd'     => "root",
    'name'       => "live",
    'charset'    => "utf8",
    'setname'    => true,
    'persistent' => false, //MySQL长连接
);

return $db;

**Comment by matyhtf** [comment]
CLMySQL 请勿使用。
