### ISSUE TITLE
PHP Warning:  Declaration of Swoole\Database\MySQLi::query($sql) should be compatible with mysqli::query($query, $resultmode = NULL) in /vagrant/www/framework/libs/Swoole/Database/MySQLi.php on line 11

### ISSUE THREAD

**Issue by cfanbo** [matyhtf/framework#157]
明明用的是pdo的，也提示这个问题？

PHP 7.1.6 (cli) (built: Jun 23 2017 13:27:09) ( ZTS )

**Comment by zhaojianhui129** [comment]
我这里也有这个问题，当php 升级到7.1.6之后就会报错，这是由于这个类中的方法和继承类\mysqli的query方法一致，但是参数却不一致导致报错了，期待韩老师能调整发布一下，现在我都是手动改的代码
