### ISSUE TITLE
MySQL.php 这个文件中的mysql_ping在PHP7中会报错？

### ISSUE THREAD

**Issue by waterloo3122** [matyhtf/framework#166]
根据 mysql_ping 的文档 （ http://php.net/manual/en/function.mysql-ping.php ），PHP7中已经没有这个函数，framework/libs/Swoole/Database/MySQL.php这个文件使用了这个函数进行连接状态检测，在PHP7中会报错吧？

**Comment by matyhtf** [comment]
`PHP7` 请使用 `mysqli` ，修改你的`db.php`配置
