### ISSUE TITLE
Class 'Redis' not found

### ISSUE THREAD

**Issue by hzysoft** [matyhtf/framework#176]
PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /mnt/hgfs/Workspace/cc_chat4/libs/Swoole/Component/Redis.php:79
Stack trace:
#0 /mnt/hgfs/Workspace/cc_chat4/libs/Swoole/Component/Redis.php(72): Swoole\Component\Redis->connect()
#1 /mnt/hgfs/Workspace/cc_chat4/libs/factory/redis.php(25): Swoole\Component\Redis->__construct(Array)
#2 /mnt/hgfs/Workspace/cc_chat4/libs/Swoole/Swoole.php(466): require('/mnt/hgfs/Works...')
#3 /mnt/hgfs/Workspace/cc_chat4/libs/Swoole/Swoole.php(422): Swoole->loadModule('redis')
#4 /mnt/hgfs/Workspace/cc_chat4/services/Storage.php(15): Swoole->__get('redis')

Please Help

**Comment by heibor** [comment]
我也是这样的，难道是命名空间出错，还是$this->_redis = new \Redis();写法有问题?

或者是需要配置.ini文件

**Comment by heibor** [comment]
这个神奇的问题

**Comment by heibor** [comment]
大神哈，我一直没搞懂这个redis不能用的原因。
