### ISSUE TITLE
框架中的FastCGI协议是不是不完整啊？

### ISSUE THREAD

**Issue by cclehui** [matyhtf/framework#180]
onReceive 中貌似并未对需要多次 onReceive 的情况做处理 ？  不是怎么理解其中的逻辑， 貌似作者认为一次 onReceive  就拿到了所有的FastCGI请求的数据？

**Comment by heibor** [comment]
等你付费后就完整了

**Comment by heibor** [comment]
中国的开源精神确实不够好

**Comment by cclehui** [comment]
后来找到了一个开源的fastcgi协议解析， 可以看看这个： lisachenko/protocol-fcgi ，  我把它集成到了我的框架中[SwooleGlue](https://github.com/cclehui/SwooleGlue)
