### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [matyhtf/framework#209]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by sy-records** [comment]
You can send it to lufei@swoole.com

**Comment by zidingz** [comment]
Thanks! I will send an email to you soon. Also, if it saves you time, here's a PR (https://github.com/matyhtf/framework/pull/210) to help future security researchers get in touch.
